### ISSUE TITLE
DB가.....

### ISSUE THREAD

**Issue by lullulala** [2021-SMHRD-KDT-IoT-1/Soony#38]
DB를 oracle로 보내고 싶은데 아두이노는 mysql밖에 안된다고 써있어서요...ㅠㅜ

**Comment by kyg4914** [comment]
DB를 MySQL로 연동하거나 Oracle DB를 연결하는 JSP 파일을 서버에 만든 다음에 그 파일을 이용해서 Oracle에 접근해야 합니다
